#!/bin/sh

### BEGIN INIT INFO
# Provides:          nrpe
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop the nrpe daemon.
# Description:       Enable service provided by daemon.
### END INIT INFO

# Contributed by Andrew Ryder 06-22-02
# Slight mods by Ethan Galstad 07-09-02

NrpeBin=/usr/local/nagios/bin/nrpe
NrpeCfg=/usr/local/nagios/etc/nrpe.cfg

test -f $NrpeBin || exit 0

case "$1" in
start)	echo -n "Starting nagios remote plugin daemon: nrpe"
        start-stop-daemon --start --quiet --exec $NrpeBin -- -c $NrpeCfg -d
        echo "." 
	;;
stop)	echo -n "Stopping nagios remote plugin daemon: nrpe"
        start-stop-daemon --stop --quiet --exec $NrpeBin
        echo "."
        ;;
restart) echo -n "Restarting nagios remote plugin daemon: nrpe"
        start-stop-daemon --stop --quiet --exec $NrpeBin
	sleep 1
        start-stop-daemon --start --quiet --exec $NrpeBin -- -c $NrpeCfg -d
        echo "."
        ;;
reload|force-reload) echo -n "Reloading configuration files for nagios remote plugin daemon: nrpe"
	# nrpe reloads automatically
        echo "."
        ;;
*)	echo "Usage: /etc/init.d/nrpe start|stop|restart|reload|force-reload"
        exit 1 
        ;;
esac
exit 0
